#!/usr/bin/python

settings = """-- This file is now generated by a simple config generator.
-- Just run http://github.com/rcbau/hacks/lsync/generator.py from the
-- /etc/lsync directory and pipe the output to /etc/lsync/lsyncd.conf.lua

settings = {
   logfile    = "/var/log/lsyncd/lsyncd.log",
   statusFile = "/var/log/lsyncd/lsyncd-status.log",
   statusInterval = 5,
   pidfile = "/var/run/lsyncd.pid"
}

"""

sync = """sync{
        default.rsync,
        source="%(source)s/",
        target="%(target)s:%(source)s/",
        rsyncOps={"%(flags)s", "-e", "/usr/bin/ssh -i /root/.ssh/id_rsa.lsyncd -o StrictHostKeyChecking=no"}
}
"""
